Clean usage of deprecated products, fix nextChargeDate
HedvigInsurance/payment-service pull request #127
Opened 2020-10-23 10:16 UTC by vonElfvin

2020-10-23 10:19 UTC, FredrikAreschoug approved these changes
Nice work!

2020-10-23 10:19 UTC, FredrikAreschoug commented on payment-service/src/main/java/com/hedvig/paymentservice/services/bankAccounts/BankAccountServiceImpl.java
> +  //TODO: Handle red days
That is going to be fun! :smile:

2020-10-23 10:21 UTC, meletios requested changes
One comment for the charging date logic

2020-10-23 10:21 UTC, meletios commented on payment-service/src/main/java/com/hedvig/paymentservice/services/bankAccounts/BankAccountServiceImpl.java
> +    return chargeDateThisMonth;
do we need to see if the member's contract is active? 

If its *not* active, the clients are expecting null

2020-10-26 13:38 UTC, meletios approved these changes

2020-10-26 13:39 UTC, merged