[HVG-665] Bump Adyen lib, handle autorescue notificatons
HedvigInsurance/payment-service pull request #146
Opened 2020-12-10 13:18 UTC by vonElfvin

Documentation: https://docs.adyen.com/checkout/auto-rescue

Why?
- We want to enable auto-rescue of failed charges due to insufficient funds

What?
- Handle unsuccessful AUTHORISATION notifcations that are going to retry without cancelling, not taking any action with it yet.
- Handle "auto rescue processes ended" notification by applying an event, not taking any action with it yet.

2020-12-10 13:45 UTC, johantjellden commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/adyenTransaction/commands/ReceiveAdyenTransactionUnsuccessfulRetryResponseCommand.kt
> +class ReceiveAdyenTransactionUnsuccessfulRetryResponseCommand(
Should this be a data class?

2020-12-10 13:45 UTC, johantjellden commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/adyenTransaction/commands/ReceivedAdyenTransactionAutoRescueProcessEndedFromNotificationCommand.kt
> +    val transactionId: UUID,
@TargetAggregateIdentifier ;)

2020-12-10 13:48 UTC, johantjellden commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +        if (adyenNotification.additionalData != null && adyenNotification.additionalData["retry.rescueScheduled"] == "true") {
I think that you can nullcoalece here: `adyenNotification.additionalData?.get("retry.rescueScheduled") == "true"`

2020-12-10 13:50 UTC, johantjellden commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +            )
In this function it seems like we decide on a command and then send it. I think this could become more clear if we first selected the command and then sent it on the last line.
I could be wrong but it might be worth a try :)

2020-12-10 13:52 UTC, johantjellden requested changes
Awesome work! I did not read the adyen docs so I cant comment on whether it will work correct in that way. Should I do that?

2020-12-10 13:58 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +        if (adyenNotification.additionalData != null && adyenNotification.additionalData["retry.rescueScheduled"] == "true") {
Yea I did that before but then I have to null assert afterwards

2020-12-10 13:58 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +            )
I'll give it a go :)

2020-12-10 14:48 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +        if (adyenNotification.additionalData != null && adyenNotification.additionalData["retry.rescueScheduled"] == "true") {
Actually I didn't have to, weird 🤷

2020-12-10 14:49 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +            )
Done

2020-12-10 14:50 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/adyenTransaction/AdyenTransaction.kt
> +            if (response.resultCode!! == PaymentsResponse.ResultCodeEnum.REFUSED && response.additionalData?.get("retry.rescueScheduled") == "true") {
TODO: Write a test for this

2020-12-17 15:10 UTC, AlexSJ1990 submitted a review, later dismissed
Looks really nice!

2020-12-18 14:52 UTC, merged