add adyenAccountEventListener to separate from memberEventListener
HedvigInsurance/payment-service pull request #163
Opened 2021-01-27 15:02 UTC by AlexSJ1990

# Jira Issue: [] 

## What?
- 

## Why?
- 

## Optional checklist
- [ ] Boyscouted
- [ ] Unit tests written
- [ ] Tested locally

2021-01-27 15:55 UTC, vonElfvin reviewed
Nice to have, unsure what you'll use it for (especially since the description is empty 😇 )

2021-01-27 15:55 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/adyenAccount/AdyenAccount.kt
> +)
A bonus that is usually good to have
```suggestion
@Entity
data class AdyenAccount(
    @Id
    val memberId: String,
    var recurringDetailReference: String,
    var accountStatus: AdyenAccountStatus
) {
   @field:CreationTimestamp(updatable=false)
   lateinit var createdAt: Instant
   @field:UpdateTimestamp
   lateinite var updatetAt: Instant
}
```

2021-01-27 15:55 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/adyenAccount/AdyenAccountEventListener.kt
> +    }
Since `save` is `createOrUpdate` by default the checking is redundant:
```suggestion
    private fun createOrUpdateAndSave(memberId: String, recurringDetailReference: String, accountStatus: AdyenAccountStatus) {
        adyenAccountRepository.save(AdyenAccount(memberId, recurringDetailReference, accountStatus))
    }
```

2021-01-27 15:55 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/adyenAccount/AdyenAccountRepository.kt
> +interface AdyenAccountRepository : CrudRepository<AdyenAccount, String>
Don't remember exact reason but I think Jpa has a bit more power in it 🤔 
```suggestion
interface AdyenAccountRepository : JpaRepository<AdyenAccount, String>
```

2021-01-28 08:32 UTC, meletios commented on payment-service/src/main/java/com/hedvig/paymentservice/query/adyenAccount/AdyenAccountEventListener.kt
> +    }
🤯  niiiiiice! 🧠

2021-01-28 14:54 UTC, vonElfvin requested changes
Good idea to fix these issues! I think this a bit too much for one PR. Especially the removal of the old event handlers and entity properties. This one is a bit too much of a "Big Bang Release". Also having the member id as primary key for the AdyenAccount Entity sounds subpar compared to having another id with the member id as a property. This way the member can once again only have one account?

2021-01-28 14:54 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/adyenTokenRegistration/AdyenTokenRegistrationEventListener.kt
> -        }
Does it hurt to keep these around though? Feels iffy to completely remove the old before we know the new works

2021-01-28 14:54 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/member/MemberEventListener.java
> -        Optional<Member> member = memberRepository.findById(e.getMemberId());
Let's keep these around since we have no clear reason as to why we should remove it. We can @Deprecate them or something but let's not remove them if the new solution isn't better. May as well remove it after that is confirmed

2021-01-28 14:54 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/member/MemberEventListener.java
> -    public void on(AdyenAccountUpdatedEvent e) {
Same here

2021-01-28 14:54 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/member/entities/Member.java
> -
I'd say keep these around as well. At least put them in a separate PR. Same with the rest really

2021-01-28 14:54 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/query/adyenAccount/AdyenAccount.kt
> +    val memberId: String,
Having the member id as primary key sounds like the same mistake as before? Don't we want to keep them around and return the most relevant one?

2021-01-28 14:54 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/services/adyen/AdyenServiceImpl.kt
> +        val adyenAccount = adyenAccountRepository.findById(request.memberId).orElse(null)
If we want to do this properly we should do the backfill first, look at it and make sure it works, and then move over the functionality to the new projection

2021-01-28 14:56 UTC, FredrikAreschoug approved these changes
Looks good, I'm gussing you are aware but you removed `Should_ReturnDirectDebitStatus_WhenMemberHasDirectDebit` without really replacing it something. If that is fine I'm all for :+1:

2021-01-29 12:24 UTC, meletios approved these changes

2021-01-29 12:36 UTC, merged