Feature/payouts different accounts
HedvigInsurance/payment-service pull request #170
Opened 2021-02-04 10:32 UTC by vonElfvin

# Jira Issue: [HVG-841]

## What?
- Use different payout accounts for different carriers when making claim payouts

## Why?
- So we can have members with claims for HDI/HEdvig/Other as a carrier

## Optional checklist
- [x] Codecouted
- [x] Unit tests written
- [ ] Tested locally

2021-02-05 08:23 UTC, meletios requested changes
Sweet, i think it would be valuable to be more specific with the account names.

2021-02-05 08:23 UTC, meletios commented on payment-service/src/main/java/com/hedvig/paymentservice/configuration/Trustly.java
> +    String passwordClaimX;
Not sure if claimx is very intuitive for a developer that doesn't know the back story. 
Shall we rename the claim credential to 

trustly.claim.hedvig.*
trustly.claim.hdi.*

I think it makes more sense right?

2021-02-05 08:23 UTC, meletios commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/payments/Member.kt
> +
extra space?

2021-02-05 08:23 UTC, meletios commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/payments/events/upcasters/PayoutCreatedEventUpCaster.java
> -          element.addElement("handler");
Do we care about the previous upcaster? i guess we should not change that, right?

2021-02-05 08:23 UTC, meletios commented on trustly-client/src/main/java/com/hedvig/paymentService/trustly/Account.java
> +  CLAIM_X,
```suggestion
  CLAIM_HDI,
  CLAIM_HEDVIG,
```

2021-02-05 08:23 UTC, meletios commented on trustly-client/src/main/java/com/hedvig/paymentService/trustly/security/SignatureHandler.java
> +    final String passwordClaimX,
```suggestion
    final String usernameClaimHedvig,
    final String passwordClaimHedvig,
```

2021-02-08 16:34 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/payments/events/upcasters/PayoutCreatedEventUpCaster.java
> -          element.addElement("handler");
Upcasts without values do nothing, thus this is more or less removing 3 lines that don't do anything :)

2021-02-08 16:34 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/payments/Member.kt
> +
Ktlint 🤷

2021-02-08 16:34 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/configuration/Trustly.java
> +    String passwordClaimX;
I agree

2021-02-09 13:46 UTC, meletios approved these changes
Nice, shall we add a feature flag for the Adyen payout?

2021-02-09 13:46 UTC, meletios commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/payments/Member.kt
> +            }
We should add a feature flag here as well. Just to not block the Swedish payout splitting. Or?

2021-02-09 15:31 UTC, vonElfvin commented on payment-service/src/main/java/com/hedvig/paymentservice/domain/payments/Member.kt
> +            }
This is inside the adyen one so it should be fine 👍

2021-02-09 15:31 UTC, merged